<a href="https://colab.research.google.com/github/FilipeLima/Intro_Data_Science/blob/main/Introdu%C3%A7%C3%A3o_ao_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introdução ao Pandas

## Acessando arquivos

[Link para documentação da NumPy (em inglês)](https://numpy.org/pt/learn/)

[Link para documentação da Pandas (em inglês)](https://pandas.pydata.org/docs/)

[Tutorial de Pandas](https://www.datacamp.com/pt/tutorial/pandas)

In [2]:
#Carregando as bibliotecas Numpy e Pandas
import numpy as np
import pandas as pd

### Criar Dataframe

Um *dataframe* deve ser retangular, cada coluna, também chamada de variável, deve ter o mesmo tipo de arquivo e o mesmo tamanho.

É importante que cada coluna tenha um nome fácil de lembrar e descritivo dos dados. Ex: "Nome" ao invés de "nm" ou "n". "gini" ou "indice_de_gini" ao invés de "gn".

In [ ]:
df={'nome':['Ana','Marco','Gabriel','Filipe'],
    'idade':[23,25,29,41],'fumante':[False,False,False,True]}
print(df)
df=pd.DataFrame(df)
df

{'nome': ['Ana', 'Marco', 'Gabriel', 'Filipe'], 'idade': [23, 25, 29, 41], 'fumante': [False, False, False, True]}

      nome  idade  fumante
0      Ana     23    False
1    Marco     25    False
2  Gabriel     29    False
3   Filipe     41     True

In [ ]:
df['nome']

0        Ana
1      Marco
2    Gabriel
3     Filipe
Name: nome, dtype: object

In [ ]:
df2=[[1,2,3],[3,2,1],[1,1,1]]
print(df2)
df2=pd.DataFrame(df2)
df2

[[1, 2, 3], [3, 2, 1], [1, 1, 1]]

   0  1  2
0  1  2  3
1  3  2  1
2  1  1  1

### Abrindo arquivo Excel

In [ ]:
df=pd.read_excel('dataframe.xlsx')
df
#NaN significa Not-A-Number (não é um número)
#NA - Not Available (Não está disponível)

      NOME   VA1  VA2   VA3  FINAL
0      Ana   7.0  9.0   NaN    NaN
1  Beatriz   6.5  5.5  10.0    NaN
2   Carlos   3.0  3.0   3.0    5.0
3    David   8.0  5.0   7.0    NaN
4  Eriston   5.0  5.0   5.0    5.0
5   Filipe   2.0  3.0   2.0    NaN
6  Gabriel   5.5  5.5   5.0    3.0
7    Hélio  10.0  4.0   8.0    NaN
8  Irlanda   6.5  5.5   5.0    6.0
9  Joaquim   5.0  5.5   3.0    4.0

In [ ]:
df['VA1']

0     7.0
1     6.5
2     3.0
3     8.0
4     5.0
5     2.0
6     5.5
7    10.0
8     6.5
9     5.0
Name: VA1, dtype: float64

### Abrindo Arquivo CSV

csv significa *Comma-Separated Values* (Valores separados por vírgula).

### Parâmetros comuns de `pd.read_csv`

`pd.read_csv()` é uma função poderosa para ler dados CSV. Aqui estão alguns de seus parâmetros mais comuns e suas explicações:

*   **`filepath_or_buffer`**: O caminho para o arquivo CSV (string), URL ou um objeto com um método `read()`. Este é o único parâmetro obrigatório.

*   **`sep`** (ou `delimiter`): Caractere ou string a ser usado como separador entre os valores. O padrão é a vírgula (`,`).

*   **`header`**: Linha a ser usada como nomes das colunas. O padrão é `0` (a primeira linha). Pode ser `None` se o arquivo não tiver cabeçalho, ou uma lista de inteiros para um cabeçalho de várias linhas.

*   **`names`**: Lista de nomes de colunas a serem usados. Útil quando o arquivo não tem cabeçalho (`header=None`) ou para renomear colunas existentes.

*   **`index_col`**: Coluna a ser usada como o índice do DataFrame. Pode ser um nome de coluna ou um número inteiro. Se for `None` (o padrão), um índice numérico padrão será criado.

*   **`dtype`**: Dicionário de colunas para tipos de dados. Por exemplo, `{'coluna_x': float, 'coluna_y': str}`. Permite forçar um tipo de dado específico para uma coluna durante a leitura.

*   **`engine`**: O mecanismo de parser a ser usado. Pode ser `'c'` (mais rápido, padrão) ou `'python'` (mais flexível para alguns casos).

*   **`nrows`**: Número de linhas a serem lidas do arquivo (útil para pré-visualizar arquivos grandes).

*   **`skiprows`**: Número de linhas a pular no início do arquivo, ou uma lista de índices de linhas a pular.

*   **`na_values`**: String ou lista de strings para serem reconhecidas como valores `NaN` (valores ausentes). O padrão inclui várias strings comuns como `'NA'`, `'#N/A'`, etc.

*   **`parse_dates`**: Booleano ou lista de colunas para tentar analisar como datas. Se for `True` e não for especificado, tentará analisar o índice ou todas as colunas.

*   **`encoding`**: Codificação para usar na leitura do arquivo (e.g., `'utf-8'`, `'latin1'`).

*   **`decimal`**: Caractere a ser reconhecido como separador decimal (e.g., `','` para arquivos em português/europeu).

*   **`thousands`**: Caractere a ser reconhecido como separador de milhares (e.g., `'.'` para arquivos em português/europeu).

In [ ]:
df2=pd.read_csv('dataframe.csv',decimal=',',thousands='.')
df2

      NOME   VA1  VA2   VA3  FINAL
0      Ana   7.0  9.0   NaN    NaN
1  Beatriz   6.5  5.5  10.0    NaN
2   Carlos   3.0  3.0   3.0    5.0
3    David   8.0  5.0   7.0    NaN
4  Eriston   5.0  5.0   5.0    5.0
5   Filipe   2.0  3.0   2.0    NaN
6  Gabriel   5.5  5.5   5.0    3.0
7    Hélio  10.0  4.0   8.0    NaN
8  Irlanda   6.5  5.5   5.0    6.0
9  Joaquim   5.0  5.5   3.0    4.0

In [ ]:
df2['VA2']

0    9.0
1    5.5
2    3.0
3    5.0
4    5.0
5    3.0
6    5.5
7    4.0
8    5.5
9    5.5
Name: VA2, dtype: float64

### Carregando arquivos do Google Drive

In [ ]:
fraldas=pd.read_excel("/content/drive/MyDrive/Fraldas.xlsx")
fraldas

,marca,quantidade,tamanho,peso inicial,peso final,roupinha
0,Cremer Magic Care,30,P,3,5,Não
1,Cremer Magic Care,30,P,3,5,Não
2,Cremer Magic Care,30,P,3,5,Não
3,Cremer Magic Care,30,P,3,5,Não
4,Amorável,30,M,5,10,Não
5,Amorável,30,M,5,10,Não
6,Cremer Magic Care,26,M,4,9,Não
7,Cremer Magic Care,26,M,4,9,Não
8,Cremer Magic Care,26,M,4,9,Não
9,Huggies Tripla Proteção,42,M,2021-05-05 00:00:00,2021-05-09 00:00:00,Não
10,Huggies Tripla Proteção,42,M,2021-05-05 00:00:00,2021-05-09 00:00:00,Não
11,Huggies Tripla Proteção,54,M,2021-05-05 00:00:00,2021-05-09 00:00:00,Não
12,Huggies Tripla Proteção,54,M,2021-05-05 00:00:00,2021-05-09 00:00:00,Não
13,Huggies Tripla Proteção,36,G,9,2021-05-12 00:00:00,Não
14,Huggies Tripla Proteção,32,XG,12,15,Não
15,Huggies Tripla Proteção,32,M,2021-05-05 00:00:00,2021-05-09 00:00:00,Não
16,Huggies Tripla Proteção,32,M,2021-05-05 00:00:00,2021-05-09 00:00:00,Não
17,Huggies Tripla Proteção,42,M,2021-05-05 00:00:00,2021-05-09 00:00:00,Não
18,Looney Tunes,70,M,5,2021-05-09 00:00:00,Não
19,Amorável,34,P,2021-05-03 00:00:00,5,Não
20,Mamy Poko Fralda-Calça,34,G,9,14,Sim
21,Mamy Poko Fralda-Calça,28,XG,12,17,Sim
22,Huggies Supreme Care,32,G,9,2021-05-12 00:00:00,Não
23,Huggies Supreme Care,44,P,0,6,Sim
24,Huggies Supreme Care,32,G,9,2021-05-12 00:00:00,Não
25,Huggies Supreme Care,64,G,9,2021-05-12 00:00:00,Não
26,Huggies Supreme Care,64,G,9,2021-05-12 00:00:00,Não
27,Huggies Supreme Care,64,G,9,2021-05-12 00:00:00,Não
28,Huggies Supreme Care,60,G,9,2021-05-12 00:00:00,Sim
29,Huggies Supreme Care,60,G,9,2021-05-12 00:00:00,Sim
30,Huggies Supreme Care,60,G,9,2021-05-12 00:00:00,Sim
31,Huggies Supreme Care,60,G,9,2021-05-12 00:00:00,Sim
32,Huggies Supreme Care,32,G,9,2021-05-12 00:00:00,Não
33,Huggies Supreme Care,30,G,9,2021-05-12 00:00:00,Sim
34,Huggies Supreme Care,30,G,9,2021-05-12 00:00:00,Sim
35,Personal Soft & Protect,36,P,0,6,Não
36,Sapeka,6,G,9,13,Não
37,Pampers supersec,40,G,9,13,Sim

### Estatística Descritiva

In [ ]:
df2

      NOME   VA1  VA2   VA3  FINAL
0      Ana   7.0  9.0   NaN    NaN
1  Beatriz   6.5  5.5  10.0    NaN
2   Carlos   3.0  3.0   3.0    5.0
3    David   8.0  5.0   7.0    NaN
4  Eriston   5.0  5.0   5.0    5.0
5   Filipe   2.0  3.0   2.0    NaN
6  Gabriel   5.5  5.5   5.0    3.0
7    Hélio  10.0  4.0   8.0    NaN
8  Irlanda   6.5  5.5   5.0    6.0
9  Joaquim   5.0  5.5   3.0    4.0

In [ ]:
df['VA1'].describe()

count    10.000000
mean      5.850000
std       2.321996
min       2.000000
25%       5.000000
50%       6.000000
75%       6.875000
max      10.000000
Name: VA1, dtype: float64

In [ ]:
df['VA2'].describe()

count    10.000000
mean      5.100000
std       1.696401
min       3.000000
25%       4.250000
50%       5.250000
75%       5.500000
max       9.000000
Name: VA2, dtype: float64

### Conectando ao Google Drive

O Colab tem uma função Python para conectar o Notebook diretamente ao Google Drive do usuário. Assim, um usuário pode acessar seu banco de dados na nuvem.

In [1]:
#Importar a função drive do pacote google.colab
from google.colab import drive
#Montar conectar o google drive ao notebook
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### Baixando arquivo via URL

Nesse exemplo, vamos usar um dataframe que está no repositório do curso. Precisamos de um link para o arquivo *Dataset_economia_ciencia_dados.csv*. Basta abrir o arquivo no repositório e procurar o botão *Raw*. Ele abrirá uma guia para o arquivo. Daí basta copiar o link.

In [3]:
url="https://raw.githubusercontent.com/FilipeLima/Intro_Data_Science/60103735973725760148d65f372332d3569895ab/dataset_economia_ciencia_dados.csv"

df=pd.read_csv(url)
df

     educacao_anos  idade        regiao  renda_mensal
0               10     42         Norte       6306.57
1                7     24  Centro-Oeste       3455.62
2               16     26       Sudeste       8766.23
3               14     41           Sul       8478.63
4               11     18      Nordeste       6856.44
..             ...    ...           ...           ...
115             16     49      Nordeste       9820.81
116             12     21       Sudeste       7574.38
117             16     28       Sudeste       8556.80
118             16     34           Sul       9265.56
119              4     55       Sudeste       3701.79

[120 rows x 4 columns]